export const ADMIN_PERMISSIONS = {
  VIEW_TESTS: "view_tests",
  VIEW_BATCHES: "view_batches",
  VIEW_STUDENTS: "view_students",
  VIEW_EVENTS: "view_events",
  VIEW_QUESTION_BANK: "view_question_bank",
  CREATE_TEST: "create_test",
  EDIT_TEST: "edit_test",
  DELETE_TEST: "delete_test",
  PUBLISH_TEST: "publish_test",
  MANAGE_QUESTIONS: "manage_questions",
  VIEW_RESOURCES: "view_resources",
  MANAGE_RESOURCES: "manage_resources",
  MANAGE_BATCHES: "manage_batches",
  MANAGE_EVENTS: "manage_events",
  VIEW_REPORTS: "view_reports",
  EXPORT_REPORTS: "export_reports",
  MANAGE_STUDENTS: "manage_students",
  BULK_IMPORT: "bulk_import",
  MANAGE_ADMINS: "manage_admins",
  MANAGE_DEPARTMENTS: "manage_departments",
  VIEW_ANALYTICS: "view_analytics",
  MANAGE_COLLEGE_SETTINGS: "manage_college_settings",
};
